Tweaked install

diff --git a/tp b/tp
--- a/tp
+++ b/tp
@@ -4,8 +4,12 @@
 # File  : tp.sh
 # Date  : 07/17/17
 # -----------------------------------------------------------------------------
-# Holds machine type value (MACKLIN/WIN)
+
+
+# global variables
 machine=""
+directory=""
+
 
 usage()
 {
@@ -17,11 +21,12 @@ usage()
     echo "Options:"
     echo "      -a [dir name]            Add directory to teleport list"
     echo "      -d [dir name]            Remove directory from list$"
-    echo "      -g                       Get all directories from list and print name"
+    echo "      -g [dir name]            Goes to specified directory"
     echo "      -h                       Prints help/usage string"
     echo "      -m [dir name] [dir name] Move/Rename name in list to a different name"
+    echo "      -p                       Prints all path variables currently in tp"
     echo "      -r [dir name]            Remove directory name from list"
-    echo "      -R Remove all            directories"
+    echo "      -R                       Remove all directories"
     echo "      -t [dir name]            Test directory name by printing full path of directory"
     echo "      -u                       Update teleport list"
     echo "      -v                       Print current version of teleport"
@@ -41,24 +46,41 @@ update()
 make()
 {
     # checks file level then dir level to make sure existance of tp directory
-    if [ ! -f ~/.bin/directories.txt ]; then
-        if [ ! -d ~/.bin ]; then 
-          mkdir ~/.bin
+    if [[ "$machine" == "WINNY" ]]; then
+        if [ ! -f ~/.bin/tp_variables.bat ]; then
+            if [ ! -d ~/.bin ]; then 
+                mkdir ~/.bin
+            fi
+            touch ~/.bin/tp_variables.bat
         fi
-        touch ~/.bin/directories_aliases
+    elif [[ "$machine" == "MACKY" ]]; then
+        if [ ! -f ~/.teleport/.aliases ]; then
+            if [ ! -d ~/.teleport ]; then
+                mkdir ~/.teleport
+            fi
+            touch ~/.teleport/tp_aliases
+        fi
     fi
 }
 
 load()
 {
     # load aliases into shell by running alias commands
-    if [ ! -f ~/.bin/directories_alias ]; then
-        echo "alias file not found"
-        exit -1
-    fi
-    while IFS=' ' -r line || [[ -n "$line" ]]; do
-        echo  "line: $line"
-    done < ~/.bin/directories_alias
+        if [ ! -f ~/.bin/.teleport_aliases ]; then
+            echo "alias file not found"
+            exit -1
+        fi
+        echo "reading files"
+        echo $PWD
+        while IFS=' ' read -r line || [[ -n "$line" ]]; do
+            echo "---- $1"
+            if [[ *"$1"*="$line" ]]; then
+                echo matches
+                $mod="echo '$line'|set"
+                export $line
+                echo "$line"
+            fi
+        done < ~/.bin/.teleport_aliases.bat
 }
 unload()
 {
@@ -69,28 +91,37 @@ unload()
 addDir()
 {
     make
-    echo -e "alias $1=$PWD" >> ~/.bin/directories_aliases
-    echo "Created TP Link: $1"
-    load
+    echo -e "$1=$2" >> ~/.bin/.teleport_aliases
+    source ~/.bin/.teleport_aliases
+    echo "add done"
 }
 
+
+goto()
+{
+    echo 'goto'    
+}
 
 delDir()
 {
     make
     echo "$1"
-    #set -i.bak '/"$(2)/d' ~/.bin/directories_aliases
+    #set -i.bak '/"$(2)/d' ~/.bin/.teleport_aliases
 }
 
 
 delDirs()
 {
-    
-    rm -f ~/.bin/directories_aliases
-    touch ~/.bin/directories_aliases
+   
+    if [[ "$machine" == "WINNY" ]]; then 
+        rm -f ~/.bin/.teleport_aliases
+        touch ~/.bin/.teleport_aliases
+    fi
     echo "Cleared TP Dirations"
 }
-
+# -----------------------------------------------------------------------------
+# Functions End | Argument Parsing Start
+# -----------------------------------------------------------------------------
 
 # checks for empty args
 if [[ $# == "0" ]]; then
@@ -99,37 +130,48 @@ fi
 
 # get machine type
 case "$(uname)" in
-    LINUX*|DARWIN*)
-        machine="MACKLIN"
-    ;;
-    CYGWIN*|MINGW*|MYSYS)
-        machine="WIN"
-    ;;  
+    LINUX*|DARWIN*) machine="MACKY" ;;
+    CYGWIN*|MINGW*) machine="WINNY" ;;  
 esac
 
 # parses input args
-while getopts "r:Ra:hvu" opt; do
+while getopts "r:Ra:A:c:hvu" opt; do
     case $opt in
-        \?)
-            echo "Invalid option -$OPTARG" && exit -1
-        ;;
-        h)
-            usage && exit 0
-        ;;
-        v)
-            version && exit 0
-        ;;
+        \?) echo "Invalid command" && exit -1;;
         a)
-            addDir "$2" && exit 1
+            if [[ $3 == "" ]]; then
+              echo "tp: option will add current working directory"
+              addDir "$2" "$PWD"
+              exit 1
+            elif [ -d "$3" ]; then
+                if [ "$machine" == "WINNY" ]; then
+                    echo "Windows Machine" 
+                    CWD="$(cygpath -aw $(PWD))"
+                else
+                    CWD="$(PWD)"
+                fi
+                echo $CWD
+                addDir "$2" "$CWD" && exit 1
+            else
+                echo "tp: second argument for option invalid: not a directory"
+                exit -1
+            fi
         ;;
-        r)
-            delDir "$2" && exit 1
-        ;;
-        R)
-            delDirs && exit 1
-        ;;
-        u)
-            update && exit 1
-        ;;
+        c)
+            if [[ $3 == "" ]]; then 
+                echo "tp: option requires a second argument -- c" 
+            fi
+            exit 1
+        ;; 
+        d) echo "delete from list" && exit 1 ;;
+        g) echo "go to path in list" && exit 1 ;;
+        h) echo "print help/usage" && exit 1 ;;
+        m) echo "move path to different name" && exit 1 ;;
+        p) echo "print all paths in list" && exit 1 ;; 
+        r) delDir "$2" && exit 1 ;;
+        R) delDirs && exit 1 ;;
+        t) echo "test path" && exit 1 ;;
+        u) update && exit 1 ;;
+        v) version && exit 1 ;;
     esac
 done
